#!/usr/bin/env bash
# scripts/refresh.sh
#
# Regenerate Hilal patches from the current Firefox source tree.
#
# This script writes one patch into patches/ for every tracked file
# in the Firefox checkout that differs from upstream HEAD, EXCLUDING
# files that we manage as overlays (branding/hilal, prefs/...).
#
# The default strategy is "one big patch" produced from the current
# `git diff HEAD`. For multi-patch workflows, commit your Hilal
# changes onto a branch in the Firefox tree and pass --from-commits;
# the script will then export one .patch per commit via git format-patch.
#
# Usage:
#   scripts/refresh.sh                       # diff HEAD -> 0001-hilal-local-changes.patch
#   scripts/refresh.sh --base <ref>          # diff against <ref> instead of HEAD
#   scripts/refresh.sh --from-commits <range>  # git format-patch <range>
#
# After running, review patches/ with `git diff` and update patches/series
# if you added or removed files.

set -euo pipefail

# shellcheck source=lib.sh
. "$(dirname "$0")/lib.sh"

require_firefox_src

MODE="diff"
BASE="HEAD"
COMMIT_RANGE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --base)
      [ $# -ge 2 ] || die "--base requires a ref"
      BASE="$2"; shift 2 ;;
    --from-commits)
      [ $# -ge 2 ] || die "--from-commits requires a commit range like origin/main..hilal"
      MODE="commits"; COMMIT_RANGE="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,22p' "$0"; exit 0 ;;
    *)
      die "Unknown argument: $1" ;;
  esac
done

# Refresh the branding overlay first: anything the developer changed
# inside the Firefox tree under branding/hilal is pulled back into
# branding/hilal in this repo, so patches stay focused on source code.
for src in "$HILAL_REPO_ROOT/branding"/*/; do
  [ -d "$src" ] || continue
  name="$(basename "$src")"
  ff_src="$HILAL_FIREFOX_SRC/browser/branding/$name"
  if [ -d "$ff_src" ]; then
    log "Refreshing branding overlay: $name <- browser/branding/$name"
    if command -v rsync >/dev/null 2>&1; then
      rsync -a --delete "$ff_src/" "$src"
    else
      rm -rf "$src"
      cp -r "$ff_src/" "$src"
    fi
  fi
done

# Likewise refresh prefs/ from the Firefox tree, file by file.
if [ -d "$HILAL_REPO_ROOT/prefs" ]; then
  (
    cd "$HILAL_REPO_ROOT/prefs"
    find . -type f ! -name '.DS_Store' ! -name '.gitkeep' -print0 | while IFS= read -r -d '' rel; do
      rel="${rel#./}"
      ff_file="$HILAL_FIREFOX_SRC/$rel"
      if [ -f "$ff_file" ]; then
        if [ "$ff_file" -ef "$rel" ]; then
          continue
        fi
        log "Refreshing prefs overlay: $rel"
        cp -f "$ff_file" "$rel"
      fi
    done
  )
fi

# Excludes: paths whose changes are managed as overlays, not as patches.
EXCLUDES=(
  ':!browser/branding/hilal'
)
# Auto-derive excludes from prefs/
if [ -d "$HILAL_REPO_ROOT/prefs" ]; then
  while IFS= read -r -d '' rel; do
    rel="${rel#./}"
    EXCLUDES+=(":!$rel")
  done < <(cd "$HILAL_REPO_ROOT/prefs" && find . -type f ! -name '.DS_Store' ! -name '.gitkeep' -print0)
fi

case "$MODE" in
  diff)
    out="$HILAL_REPO_ROOT/patches/0001-hilal-local-changes.patch"
    log "Generating $out (diff $BASE -- excludes overlays)"
    # shellcheck disable=SC2068
    diff_body="$(git -C "$HILAL_FIREFOX_SRC" diff "$BASE" -- . ${EXCLUDES[@]})"
    if [ -z "$diff_body" ]; then
      warn "No source-code changes detected vs $BASE. Removing stale patch if any."
      rm -f "$out"
    else
      {
        echo "Hilal local source changes (auto-generated by scripts/refresh.sh)"
        echo
        echo "Regenerate with:  scripts/refresh.sh --base $BASE"
        echo
        echo "$diff_body"
      } > "$out"
      log "Wrote $(wc -l < "$out") lines to $(basename "$out")"
    fi
    ;;
  commits)
    log "Exporting commits in range: $COMMIT_RANGE"
    tmpdir="$(mktemp -d)"
    trap 'rm -rf "$tmpdir"' EXIT
    # shellcheck disable=SC2068
    git -C "$HILAL_FIREFOX_SRC" format-patch \
      --no-stat --no-signature \
      -o "$tmpdir" \
      "$COMMIT_RANGE" -- . ${EXCLUDES[@]}
    # Clear old patches that we are about to replace.
    find "$HILAL_REPO_ROOT/patches" -maxdepth 1 -type f -name '*.patch' -delete
    cp "$tmpdir"/*.patch "$HILAL_REPO_ROOT/patches/"
    # Rebuild the series file from the new patch filenames.
    {
      echo "# Hilal Browser patch series."
      echo "# Auto-regenerated by scripts/refresh.sh --from-commits $COMMIT_RANGE"
      echo
      (cd "$HILAL_REPO_ROOT/patches" && ls -1 *.patch | sort)
    } > "$HILAL_REPO_ROOT/patches/series"
    log "Wrote $(ls "$HILAL_REPO_ROOT"/patches/*.patch | wc -l | tr -d ' ') patches and refreshed series."
    ;;
esac

log "Done. Review with:  git -C $HILAL_REPO_ROOT diff"
